name: Use Shared GitHub Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This is a built-in action from GitHub
      - name: Use Shared Action
        uses: rajvmalasoni/CHATOPSTEST@2.1.0.0  # Replace with the owner and repository name where the action is published, and the version tag
