name: testing github workflows
on: 
  pull_request:
    types: [opened, edited, reopened]

permissions: write-all
jobs:
    testing:
      runs-on: ubuntu-latest
      steps:
        - name: testing bash script
          run : |
              echo "Hello world"
              ls
              pwd
              sh ./temp.sh

