name: Scheduled Workflow

on:
    pull_request:
        types: [closed]
        branches:
          - master
    #push:
    #schedule:
    #- cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  build_and_update:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
      GITHUB_USERNAME: ${{ github.actor }} # Pass necessary environment variables here
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

    
      - name: Build Docker Image
        run: docker buildx build --platform linux/amd64 -t my-custom-image --load  .
         # Add a step to check if the image was built successfully
      - name: Check Docker Image
        run: docker images | grep my-custom-image 

      - name: Run Docker Container
        run: docker run --name my-container -e GITHUB_TOKEN=${{ secrets.GH_TOKEN }} -e GITHUB_USERNAME=${{ github.actor }} my-custom-image
      - name: Clean up Docker Container
        run: docker rm my-container

      - name: Clean up Docker Image
        run: docker image prune --all --force